---
title: "EDA Cleaning"
output: html_notebook
---
```{r}
# Load library
library(tidyverse)

# Assign dataframe
data <- read_csv("university_clean.csv")

data <- data %>% select(-...1)

```
# Convert categorical columns to factors
# (This is stripped out in the conversion to csv)

```{r}

data <- data %>%
        mutate(across(-c(age_at_enrollment),function(x) as.factor(x)))

str(data)

```
# VARIABLE CHANGES
# A number of variables had lots of categories with very few data points in them. I've re-categorised these into broader, more useful ones.

```{r}

# ALL OF THESE NEED TO BE TURNED INTO FACTORS AFTER THEY'RE CREATED!

# MARITAL STATUS
# Combining into 'Single' and 'Not Single'

data <- data %>% mutate (
  single = case_when(
    marital_status %in% c(1,3,4,6) ~ 1, #Single, Widower, Divorced, Legally Separated
    marital_status %in% c(2,5) ~ 0 #Married, De Facto
    ) %>%
    factor()
)

```

```{r}

# PREVIOUS_QUALIFICATION

table(data$previous_qualification)

data <- data %>% mutate(
  previous_education = case_when(
    previous_qualification %in% c(7,8,9,10,11,12,13) ~ 0, # Anything below secondary graduation
    previous_qualification %in% c(1,6,14,16) ~ 1, # Completed secondary, inc. post-secondary, less than bachelors
    previous_qualification %in% c(2,3,4,5,15,17) ~ 2 #Bachelors or above
  ) %>%
    factor(levels = c(0,1,2), ordered = TRUE) # Unlike most of the factors, education levels is ordinal
) 
# 'Frequency of higher education' in post-secondary
# Initially had 5 groups, but very little difference between 'basic education' and 'didn't finish secondary' and between 'finished secondary' and 'post-secondary, less than bachelors'. Combined further.

table(data$previous_education)

# PARENT QUALIFICATIONS
# This was troublesome. There are a number of now-discontinued qualifications that were difficult to classify.

# There are unknowns in these, which will be replaced with the mode once the data is split.

table(data$mother_qualification)

data <- data %>% mutate(
  mother_education = case_when(
    mother_qualification %in% c(9,14,20,21,25,26,27,28,7,8,10,11,12,14,17,18,19) ~ 0, #Didn't finish secondary
    mother_qualification %in% c(1,13,15,16,19,22,23,6,29,31,32) ~ 1, #Finished secondary
    mother_qualification %in% c(2,3,4,5,30,33,34) ~ 2, #Bachelors or above
    mother_qualification %in% c(24) ~ NA #Unknown
  ) %>%
    factor(levels = c(0,1,2), ordered = TRUE)
)

data <- data %>% mutate(
  father_education = case_when(
    father_qualification %in% c(9,14,20,21,25,26,27,28,7,8,10,11,12,17) ~ 0, #Didn't finish secondary
    father_qualification %in% c(1,13,15,16,19,22,23,6,29,31,32) ~ 1, #Finished secondary
    father_qualification %in% c(2,3,4,5,30,33,34) ~ 2, #Bachelors or above
    father_qualification %in% c(24) ~ NA #Unknown
  ) %>%
    factor(levels = c(0,1,2), ordered = TRUE)
)

# PARENT OCCUPATION

data <- data %>% mutate(
  mother_profession = case_when(
    mother_occupation %in% c(12,13) ~ NA, #Unknown
    mother_occupation %in% c(1) ~ 1,
    mother_occupation %in% c(2,17,18) ~ 2,
    mother_occupation %in% c(3,19) ~ 3,
    mother_occupation %in% c(4,20,21,22,23,24,25,26) ~ 4,
    mother_occupation %in% c(5,27,28,29) ~ 5,
    mother_occupation %in% c(6,30,31,32,33,44,45,46) ~ 6,
    mother_occupation %in% c(7,34,35) ~ 7,
    mother_occupation %in% c(8,36,37,38,39) ~ 8,
    mother_occupation %in% c(9,40,41,42) ~ 9,
    mother_occupation %in% c(10,43,44) ~ 10,
    mother_occupation %in% c(11,14,15,16) ~ 11
  ) %>%
    factor()
)

data <- data %>% mutate(
  father_profession = case_when(
    father_occupation %in% c(12,13) ~ NA, #Unknown
    father_occupation %in% c(1) ~ 1,
    father_occupation %in% c(2,17,18) ~ 2,
    father_occupation %in% c(3,19) ~ 3,
    father_occupation %in% c(4,20,21,22,23,24,25,26) ~ 4,
    father_occupation %in% c(5,27,28,29) ~ 5,
    father_occupation %in% c(6,30,31,32,33,44,45,46) ~ 6,
    father_occupation %in% c(7,34,35) ~ 7,
    father_occupation %in% c(8,36,37,38,39) ~ 8,
    father_occupation %in% c(9,40,41,42) ~ 9,
    father_occupation %in% c(10,43,44) ~ 10,
    father_occupation %in% c(11,14,15,16) ~ 11
  ) %>%
    factor()
)

table(data$father_occupation)

# The biggest dropout rates are in 'unknown' (no use) and 'student'!
```
# APPLICATION MODE

```{r}

data <- data %>% mutate(
      application_group = case_when(
    application_mode %in% c(1,8,9) ~ 0, # General
    application_mode %in% c(2,10,11,13,14,16,18) ~ 1, # Course/institution transfer/reenrollment
    application_mode %in% c(3,4,5,6,7,12,15,17) ~ 2 # Other
  ) %>%
    factor()
)

# TRANSFER

# From the MI scores, application mode is too related to age and previous qualification. Going to try just separating out transfer students.

data <- data %>% mutate(
        transfer = case_when(
        application_group %in% c(1) ~ 1,
        application_group %in% c(0,2) ~ 0
  ) %>%
    factor()
)
```

# PARENTS
```{r}

# SAME SEX PARENT EDUCATION/PROFESSION
# Would this correlate better with Dropout?

data <- data %>% mutate(
  same_sex_parent_education = case_when(
    gender == 1 ~ father_education,
    gender == 0 ~ mother_education
  ) %>%
    factor()
)

data <- data %>% mutate(
  same_sex_parent_profession = case_when(
    gender == 1 ~ father_profession,
    gender == 0 ~ mother_profession
  ) %>%
    factor()
)

#No, both lower.

# OPPOSITE SEX PARENT EDUCATION/PROFESSION
# Must test assumptions

data <- data %>% mutate(
  opposite_sex_parent_education = case_when(
    gender == 0 ~ father_education,
    gender == 1 ~ mother_education
  ) %>%
    factor()
)

data <- data %>% mutate(
  opposite_sex_parent_profession = case_when(
    gender == 0 ~ father_profession,
    gender == 1 ~ mother_profession
  ) %>%
    factor()
)

# Both lower

# Highest education level of parent?

data <- data %>% mutate(highest_parent_education = case_when(
    as.numeric(father_education) >= as.numeric(mother_education) ~ father_education,
    as.numeric(father_education) < as.numeric(mother_education) ~ mother_education
  ) %>%
    factor()
)

# No improvement

# Group Courses by School (Info from website)

data <- data %>% mutate(academic_school = case_when(
          course %in% c(1,2,5,7,9,14,17) ~ 0, #ESTGD
          course %in% c(4,6,8) ~ 1, #ESBE
          course %in% c(3,10,11,15,16) ~ 2, #ESECS
          course %in% c(12,13) ~ 3 #ESS
          ) %>%
          factor()
)

```
# Age

```{r}
# Under 25

data <- data %>% mutate(under_25 = ifelse(age_at_enrollment < 25, 1, 0))
data <- data %>% mutate(under_24 = ifelse(age_at_enrollment < 24, 1, 0))

#Not giving better results

data <- data %>% mutate(age_band = case_when(
          age_at_enrollment < 25 ~ 0,
          age_at_enrollment >= 25 & age_at_enrollment < 35 ~ 1,
          age_at_enrollment >= 35 & age_at_enrollment < 45 ~ 2,
          age_at_enrollment >= 45 & age_at_enrollment < 55 ~ 3,
          age_at_enrollment >= 55 ~ 4)
          )

# Not better either.

```


